# Site settings
title: koohyar
email: koohyar.dev@gmail.com
url: https://koohyar7342.github.io
description: "Android Developer"
keywords: "Android, Android Developer, kotlin, کاتلین, اندروید, توسعه دهنده اندروید "
skills: "Android Developer"
meta_author: koohyar nory

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: koohyar

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: <a href="https://github.com/jeromelachaud/freelancer-theme">freelancer-theme</a>
  location: Location
  social: شبکه‌های اجتماعی
  credits: Email

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/koohyar7342
  - title: bazaar
    url: https://cafebazaar.ir/developer/264369000187
    img: /img/bazaar-icon.png
  - title: myket
    url: https://myket.ir/developer/dev-78707
    img: /img/myket-icon.png
  - title: github
    url: https://github.com/koohyar7342

# Postal address (add as many lines as necessary)
address:
  - line: ایران
  - line: یزد

# Credits content
credits: 'koohyar.dev@gmail.com'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "modals"

